DROP TABLE IF EXISTS user CASCADE ;

CREATE TABLE user
(
    user_id  bigint generated by default as identity,
    email    varchar(255),
    login    varchar(255),
    name     varchar(255),
    password varchar(255),
    phone    varchar(255),
    role     varchar(255),
    surname  varchar(255),
    primary key (user_id)
);

DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS project_users CASCADE;

CREATE TABLE project
(
    project_id     bigint generated by default as identity,
    create_time    varchar(255),
    description    varchar(255),
    end_time       timestamp,
    project_status varchar(255),
    short_name     varchar(255),
    title          varchar(255),
    owner_user_id  bigint,
    primary key (project_id)
);
CREATE TABLE project_users
(
    user_id    bigint not null,
    project_id bigint not null
);
alter table project add constraint FKs1xrbvp32s3ue8wb75gogdcqr foreign key (owner_user_id) references user;
alter table project_users add constraint FK9at0ei37rls7vd2m6sh92668h foreign key (project_id) references project;
alter table project_users add constraint FKswc4g4h18lbxsl9obvo97lnbl foreign key (user_id) references user;

-- INSERT INTO user (user_id, email, login, name, password, phone, role, surname) values (null, 'sdcdc', 'fdfv', 've', 'dffdv', 'dsdvd', 'Admin', 'dfvf');
-- INSERT INTO project (project_id, create_time, description, end_time, owner_user_id, project_status, short_name, title) values (null, '','', '', 1, '', '', '');
-- INSERT INTO project_users( user_id ,project_id) values ( 1,1 )



