drop table if exists comments CASCADE;
drop table if exists project CASCADE;
drop table if exists project_users CASCADE;
drop table if exists task CASCADE;
drop table if exists task_users_task CASCADE;
drop table if exists user CASCADE;
create table comments
(
    comments_id bigint generated by default as identity,
    primary key (comments_id)
);
create table project
(
    project_id     bigint generated by default as identity,
    create_time    varchar(255),
    description    varchar(255),
    end_time       varchar(255),
    project_status varchar(255),
    short_name     varchar(255),
    title          varchar(255),
    owner_user_id  bigint,
    primary key (project_id)
);
create table project_users
(
    user_id    bigint not null,
    project_id bigint not null
);
create table task
(
    task_id     bigint generated by default as identity,
    date_end    varchar(255),
    date_start  varchar(255),
    description varchar(255),
    priority    varchar(255),
    task_status varchar(255),
    title       varchar(255),
    project_id  bigint,
    primary key (task_id)
);
create table task_users_task
(
    tasks_task_id      bigint not null,
    users_task_user_id bigint not null,
    primary key (tasks_task_id, users_task_user_id)
);
create table user
(
    user_id  bigint generated by default as identity,
    email    varchar(255),
    login    varchar(255),
    name     varchar(255),
    password varchar(255),
    phone    varchar(255),
    role     varchar(255),
    surname  varchar(255),
    primary key (user_id)
);
alter table project
    add constraint FKs1xrbvp32s3ue8wb75gogdcqr foreign key (owner_user_id) references user;
alter table project_users
    add constraint FK9at0ei37rls7vd2m6sh92668h foreign key (project_id) references project;
alter table project_users
    add constraint FKswc4g4h18lbxsl9obvo97lnbl foreign key (user_id) references user;
alter table task
    add constraint FKk8qrwowg31kx7hp93sru1pdqa foreign key (project_id) references project;
alter table task_users_task
    add constraint FK6yh1pvp8bashsaoi4oq0jbrr foreign key (users_task_user_id) references user;
alter table task_users_task
    add constraint FKlvel53532yqhw5psdr2fa7m4q foreign key (tasks_task_id) references task;