drop table if exists comments CASCADE;
drop table if exists project CASCADE;
drop table if exists project_users CASCADE;
drop table if exists task CASCADE;
drop table if exists user CASCADE;
drop table if exists users_task CASCADE;
create table comments
(
    comments_id bigint generated by default as identity,
    text        varchar(255),
    user_id     bigint,
    task_id     bigint,
    primary key (comments_id)
);

INSERT INTO comments(comments_id, text, task_id, user_id)
values (null, '111111111111111', 1, 4),
       (null, '222222222', 1, 4),
       (null, '33333333', 1, 4);

create table project
(
    project_id     bigint generated by default as identity,
    create_time    varchar(255),
    description    varchar(255),
    end_time       varchar(255),
    project_status varchar(255),
    short_name     varchar(255),
    title          varchar(255),
    owner_user_id  bigint,
    primary key (project_id)
);

INSERT INTO project (project_id, create_time, description, end_time, project_status, short_name, title, owner_user_id)
values (null, '2021-04-16 13:45:43', 'Project 1', null, 'IN_PROGRESS', 'ProjDip', 'Project diplom', 2),
       (null, '2020-04-11 13:30:43', 'Project 2', '2020-04-11 19:30:43', 'COMPLETED', 'Magaz', 'Magazine', 2),
       (null, '2021-01-03 03:45:43', 'Project 3', null, 'NOT_STARTED', 'Shop1', 'Online Shop', 2),
       (null, '2021-01-03 06:45:43', 'Project 4', null, 'NOT_STARTED', 'Shop2', 'Dog Shop', 3),
       (null, '2021-06-03 11:45:43', 'Project 5', null, 'POSTPONED', 'Shop3', 'Toy shop', 2);

create table project_users
(
    user_id    bigint not null,
    project_id bigint not null
);



INSERT INTO project_users(user_id, project_id)
values (2, 4),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 5),
       (4, 1),
       (4, 2);
create table task
(
    task_id     bigint generated by default as identity,
    date_end    varchar(255),
    date_start  varchar(255),
    description varchar(255),
    priority    varchar(255),
    task_status varchar(255),
    title       varchar(255),
    project_id  bigint,
    primary key (task_id)
);

INSERT INTO task (task_id, date_end, date_start, description, priority, task_status, title, project_id)
values (null, null, '2020-04-11 13:30:43', 'TASK1DESCRIPTION', 'LOW', 'NOT_STARTED', 'TITLE1TASK1', 1),
       (null, '2020-04-11 18:30:43', '2020-04-11 13:30:43', 'TASK2DESCRIPTION', 'LOW', 'COMPLETED', 'TITLE2TASK2', 1),
       (null, null, '2020-04-11 13:30:43', 'TASK3DESCRIPTION', 'LOW', 'NOT_STARTED', 'TITLE3TASK3', 1),
       (null, null, '2020-04-11 13:30:43', 'TASK4DESCRIPTION', 'LOW', 'NOT_STARTED', 'TITLE4TASK4', 4),
       (null, null, '2020-04-11 13:30:43', 'TASK5DESCRIPTION', 'LOW', 'NOT_STARTED', 'TITLE5TASK5', 4);


create table user
(
    user_id  bigint generated by default as identity,
    email    varchar(255),
    login    varchar(255),
    name     varchar(255),
    password varchar(255),
    phone    varchar(255),
    role     varchar(255),
    surname  varchar(255),
    primary key (user_id)
);

INSERT INTO user (user_id, email, login, name, password, phone, role, surname)
values (null, null, 'admin', null, '$2y$12$Mnq.GK.kwlPkPt9HZW9KI.HKQWOnSyVgweioWQR45nrMGIaq8YObm', null, 'ADMIN', null),
       (null, 'onliner@gmail.com', 'nintendo233', 'Oleg',
        '$2y$12$rKBORZNjgrMRqwEvf2LBB.Bs2hooPbYUA3NJB6ef6LQZEXyEwmsfq', '+375293542346', 'MANAGER', 'Tereshkov'),
       (null, 'zevs@gmail.com', 'anna', 'Anna', '$2y$12$S72FEcJeeZ/mW/I8.QeLDO9iG7JBXUAXL5ZFKODrIewG/IB7VVtl.',
        '+375292543246', 'USER', 'Ribalko'),
       (null, 'zevs@gmail.com', 'user', 'Saha', '$2y$12$E6qO56v1Ya7dECQ/70Llm.mcOJHrojhCmD/K1mvNK3ikTaJ.VS2Fi',
        '+375292543246', 'USER', 'Golubovich');

create table users_task
(
    user_id bigint not null,
    task_id bigint not null
);

INSERT INTO users_task(user_id, task_id)
values (3, 1),
       (3, 2),
       (3, 3),
       (2, 4),
       (2, 5),
       (4, 1),
       (4, 2);
